pep_version: 2.0.0
sample_table: metadata.csv
subsample_table: runs.csv
sample_modifiers:
  append:
    path: source1
  derive:
    attributes: [path]
    sources:
      source1: "/Users/taavi/Projects/sarscov2-upload/.tests/reads/projects/covid/{experiment}/{file}"
