name: ena_upload
channels:
  - conda-forge
  - bioconda
dependencies:
  - openpyxl
  - xlrd
  - snakemake
  - peppy
  - pip
  - pip:
     - "--editable=git+https://github.com/avilab/ena-upload-cli.git@location#egg=ena-upload-cli"
